name: secrets-app-cs-plugin
description: Plug-in para instrumentar o AWS Secret Manager.
types:
- app
inputs:
- label: TTL Cache ms
  type: text
  name: cache_item_ttl
  default: "3700000"
- label: Maximum Cache Size
  type: text
  name: max_cache_size
  default: "1024"  
- label: Version Stage
  type: text
  name: version_stage
  default: "AWSCURRENT"    
- label: Region Endpoint
  type: text
  name: region_endpoint
  default: "sa-east-1"

displayName: Secrets

picture: "plugin.png"

category: backend, secrets

compatibility:
  - net5.0
  - net6.0

about: about.md

usage: usage.md

useCase: useCase.md

implementation: implementation.md

technologies: [".NET", "C#"]  